# Generated by Django 5.2.6 on 2025-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('evaluation', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=200)),
                ('lunchprice', models.CharField(max_length=200)),
                ('dinnerprice', models.CharField(max_length=200)),
            ],
        ),
    ]
