# Generated by Django 5.2.6 on 2025-09-16 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0002_restaurant_delete_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='dinnerprice',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lunchprice',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='place',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='store_id',
        ),
    ]
