# Generated by Django 5.2.6 on 2025-09-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0004_restaurant_open_date_restaurant_restaurant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
