# Generated by Django 5.2.6 on 2025-09-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0005_restaurant_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='category',
            new_name='genre',
        ),
    ]
