# Generated by Django 5.2.6 on 2025-09-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabelog', '0006_rename_category_restaurant_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
